### ISSUE TITLE
Spring problem, terminal is reopening on each run

### ISSUE THREAD

**Issue by quolpr** [moxley/atom-ruby-test#107]
Spring is not working properly(`bin/rspec`). The problem is that spring shut down and start again on each test run. As I understand, it is happening because `atom-ruby-test` is not using current `platformio-ide-terminal` window and just open new.

https://github.com/rails/spring/issues/529

The workaround, for now, is to start spring in your OS terminal.

**Comment by nolanpro** [comment]
Fixes https://github.com/moxley/atom-ruby-test/issues/107
