### ISSUE TITLE
platformio-ide-terminal no longer supported - how do I reconfigure to use terminus?

### ISSUE THREAD

**Issue by aquaman** [moxley/atom-ruby-test#116]
I cannot install platformio-ide-terminal anymore in Atom on my Mac. The recommended new terminal package is terminus. I've installed it but I don't know how to reconfigure Ruby Test to use that window instead.

Is there a config file or setting somewhere that I can point to the new terminal package?

**Comment by aquaman** [comment]
Hey @nolanpro, did you ever hear back about taking ownership of this repo?

**Comment by nolanpro** [comment]
@aquaman Hey I've actually switched to vscode as my primary editor so I don't think i'll be able to take over this repo.

**Comment by moiristo** [comment]
Please see https://github.com/moxley/atom-ruby-test/pull/114. It's in master.
