### ISSUE TITLE
chruby support with zsh

### ISSUE THREAD

**Issue by turboladen** [moxley/atom-ruby-test#16]
For reference: https://github.com/postmodern/chruby.  I installed on OSX using Homebrew, FWIW.

I setup my test/rspec commands to use `bin/rspec --tty` (etc.).  When I run any of the tests (cmd-ctrl-r, for example), I get output in the console saying that it can't find bundler--but the ruby path that's in the backtrace is for the system ruby.  (As an aside, and I don't know if this is on you or Atom, it'd be nice to be able to copy the output from the console so I can paste in here.  I'm not able to select anything in there).  I've tried changing the commands to look like:
- `bin/rsepc --tty spec`
- `bundle exec rspec --tty spec`
- `source /usr/local/opt/chruby/share/chruby/chruby.sh; cd .; bundle exec rspec --tty spec`

Atom version: 0.115.0
Ruby test: 0.7.0

**Comment by nesQuick** [comment]
Hey,

I also just stumbled upon this, and have the same issues. That's why I'd love to see this issue reopened. A little thing I found is that calling `chruby_auto` right before the test at least helps picking up the `.ruby-version` file so my commands look like `chruby_auto && ruby -I test {relative_path}`

Maybe something like a shell setup block or such would help :)

**Comment by yock** [comment]
@nesQuick When I prefix my command with `chruby_auto` the results window says the command is not found. How are you getting Atom and/or ruby-test to load chruby in the first place?

**Comment by yock** [comment]
`source ~/.zshrc && chruby_auto && bin/rspec --tty spec`

This works, but initializing my shell every time is quite time consuming. I'd imagine I could probably load chruby this way and exclude most of the irrelevant ZSH pieces, but this still incurs a big startup cost. I wonder if there's a way to initialize this into the Atom environment itself.

**Comment by nesQuick** [comment]
@yock I created the `.zprofile` file as mentioned in a similar issue https://github.com/moxley/atom-ruby-test/issues/60 
```bash
λ  ~  cat ~/.zprofile
source ~/.zshrc
```
