### ISSUE TITLE
Add bundle support?

### ISSUE THREAD

**Issue by RSO** [moxley/atom-ruby-test#25]
When trying to run my tests I received some output stating that I should use `bundle exec` to run the tests. I manually edited the package and added `bundle exec` and now the tests work for me.

I'm not totally sure if adding `bundle exec` as a prefix to all commands will have the expected outcome for people who are not working inside of a bundle. What do you think?

I could possibly spend some more time on this and add bundle support as a setting.

**Comment by art-solopov** [comment]
While modifying the commands is a viable options, wouldn't it be nice to have a universal flag to use Bundler whenever possible, similar to the [Emacs rspec-mode](https://github.com/pezra/rspec-mode)?
