### ISSUE TITLE
Space in project directory path causing problems

### ISSUE THREAD

**Issue by moxley** [moxley/atom-ruby-test#30]
This user had a space in one of the directory names leading up to their project directory. It caused an error in the test output: `zsh:cd:1 string not in cwd...`.

See https://github.com/moxley/atom-ruby-test/issues/29.

**Comment by wkonkel** [comment]
I am also experiencing this. It seems to be a problem relating to RVM's chpwd function.

/Users/warren/.rvm/scripts/extras/bash_zsh_support/chpwd/function.sh: line 5: cd /Users/warren/Workspace/project: No such file or directory

It looks like the path isn't being passed with quotes.

**Comment by moxley** [comment]
This is resolved with 80b5c53e6a98f6dc14ad26356ef793d0a10a126d
