### ISSUE TITLE
Does not work in fish

### ISSUE THREAD

**Issue by paradox460** [moxley/atom-ruby-test#31]
There are a few problems that prevent this tool from working with fish.

First of all, the order of `['-c', '-l', testCommand]` in shell-runner.coffee is incorrect for fish, and, according to the man page, for bash. Interesting that it seems to work in bash.

`-c` is supposed to accept a string; the command to run in the shell. Placing it before `-l` passes `-l` as the command to run, which is not the intent.

The second problem is, fish does not use `&&` to run multiple commands. It uses `;` instead.

----

These changes seem pretty simple, and the only reason I have not created a PR with them is I wanted to know if you had any objections to this.

**Comment by dideler** [comment]
Also running into this problem.

If I put 'fish' as the shell, I get the following error even though fish is in my PATH:

> 'fish' could not be spawned.
Is it installed and on your path?
If so please open an issue on the package spawning the process.

If I put the full path to fish '/usr/local/bin/fish', I get the error:

> fish: Unknown command '-l'

**Comment by moxley** [comment]
The argument order of `-l` and `-c` has been fixed in #67

**Comment by moxley** [comment]
Fixed: #73
