### ISSUE TITLE
Atom.Object.defineProperty.get is deprecated.

### ISSUE THREAD

**Issue by keiter** [moxley/atom-ruby-test#39]
From the Atom deprecation cop:

> atom.workspaceView is no longer available.
> In most cases you will not need the view. See the Workspace docs for
> alternatives: https://atom.io/docs/api/latest/Workspace.
> If you do need the view, please use `atom.views.getView(atom.workspace)`,
> which returns an HTMLElement.
> ```
> Atom.Object.defineProperty.get (/Applications/Atom.app/Contents/Resources/app/src/atom.js:55:11)
> RubyTestView.initialize (/Users/keiter/.atom/packages/ruby-test/lib/ruby-test-view.coffee:20:9)
> ```

**Comment by moxley** [comment]
Fixed in v0.9.5. Thanks!
