### ISSUE TITLE
is it me?

### ISSUE THREAD

**Issue by tony-kerz** [moxley/atom-ruby-test#41]
so i recently got a new macbook and trying to re-create my environment.

installed atom and this package fresh, and when i go to settings page,
it only shows the key-bindings section, but not the settings section
(where you can enter  'test all command', etc...):

atom: 0.177.0
ruby-test: 0.9.4
osx: 10.9.5

any suggestions for troubleshooting?

best,
tony.

**Comment by moxley** [comment]
Hi @tony-kerz. This is a known issue with Atom. It tries to show the package settings without reading the package's configuration definitions. As you'll see in the [README.md](https://github.com/moxley/atom-ruby-test#configure), you must activate the package first before you can access the settings. Simply issuing any of ruby-test's commands (for instance: `cmd-ctrl-x`) will enable the package, and Atom will now display all the settings when you exit and return to ruby-test's settings panel.

**Comment by tony-kerz** [comment]
thanks @moxley i did read that bit originally and tried `cmd-ctrl-x` to no avail, but i wasn't sure that issue was responsible for the absence of the settings section. since you verified the correlation, i tried again and finally got it to work, but it didn't work the first time i tried. perhaps some nuance of what window had focus or something? anyway, i'm all set, sorry for being a dunce.
