### ISSUE TITLE
Per-project configuration for ruby-test

### ISSUE THREAD

**Issue by moxley** [moxley/atom-ruby-test#43]
When switching between multiple projects, it is a pain to reconfigure ruby-test. My day job Ruby projects are hosted in a Vagrant VM, and ruby-test needs special configuration to issue commands to the VM. Other Ruby projects run on the native machine and use the default configuration. Switching back and forth requires saving the old configuration in a copy-paste fashion, one line at a time from the ruby-test settings to a text file, then restoring the configuration, one line at a time when I switch back to the other project.

**Comment by GolecR** [comment]
I have started to use https://github.com/danielbrodin/atom-project-manager for this exact purpose.

**Comment by moxley** [comment]
:+1: Here's the package home page: https://atom.io/packages/project-manager

**Comment by kevinhughes27** [comment]
@moxley how did you configure to run tests inside vagrant?

**Comment by moxley** [comment]
@kevinhughes27: I just created this article for running ruby-test on a vagrant-based ruby project: https://github.com/moxley/atom-ruby-test/blob/master/doc/running_against_vm.md

**Comment by kevinhughes27** [comment]
awesome!
