### ISSUE TITLE
Could not locate Gemfile or .bundle/ directory

### ISSUE THREAD

**Issue by jacobwalkr** [moxley/atom-ruby-test#46]
I get this error if I use ctrl-shift-Y, ctrl-shift-T or ctrl-shift-R.

My project uses Rspec and has a valid Gemfile at its root, and I've changed the command in settings to use "bundle exec rspec" instead of just "rspec".

I also use rbenv, in case that's relevant.

**Comment by moxley** [comment]
If you open the JavaScript developer console and enter this `atom.project.getPaths()`, what does it return?

**Comment by jacobwalkr** [comment]
Whoops, sorry. My root folder wasn't my project, but rather a folder containing a number of projects. That's what was causing the issue.
