### ISSUE TITLE
Settings not available until package activated

### ISSUE THREAD

**Issue by moxley** [moxley/atom-ruby-test#5]
When first installing the package, the settings are not available to configure. They will not show up until Ruby Test is activated via one of the activation commands, like "toggle", "test-all", "test-file", etc.

I'm not sure the solution for this, other than activating the package when the editor starts up, which adds to the startup time. Ideally, Atom would activate the package when opening the package's settings page.

**Comment by andypearson** [comment]
This seems to be related to atom/settings-view#356

**Comment by moxley** [comment]
This was resolved with https://github.com/atom/settings-view/issues/356
