### ISSUE TITLE
RSpec detection not working when require (rails|spec)_helper comes from .rspec.

### ISSUE THREAD

**Issue by barelyknown** [moxley/atom-ruby-test#55]
`RSpec` allows `rails_helper` or `spec_helper` to be required by default through configuration of the `.rspec` file:
```
--color
--require rails_helper
```

Therefore, `atom-ruby-test` mistakes `RSpec` specs for `Minitest` specs when the require is omitted because it uses this `RegExp`:

```coffeescript
rspecRequireRegExp = new RegExp(/^require(\s+)['"](rails|spec)_helper['"]$/)
```

**Comment by moxley** [comment]
@barelyknown: Can you check out the latest release and let me know if that fixes it for you?

**Comment by barelyknown** [comment]
Looks good :+1: Thanks!
