### ISSUE TITLE
Duplicate test panels

### ISSUE THREAD

**Issue by djreimer** [moxley/atom-ruby-test#56]
On Atom version 0.204.0, package version 0.9.11, `ctrl-cmd-t` is opening two test panels:

![duplicate-panels](https://cloud.githubusercontent.com/assets/341387/7942862/d0feea0e-0915-11e5-9a20-e9148ae4edc3.png)

Could be something wrong with my local configuration, but wanted to file this in case. Any ideas?

**Comment by moxley** [comment]
Just a quick check, I upgraded to Atom 0.204.0 (I'm on ruby-test 0.9.11), and that issue didn't happen to me.

**Comment by djreimer** [comment]
Sorry for the false alarm. Uninstalled and reinstalled the plugin, then rebooted Atom. Seemed to take care of it.
