### ISSUE TITLE
Ability to copy text from output pane

### ISSUE THREAD

**Issue by moxley** [moxley/atom-ruby-test#6]
This is pretty important. I want to copy a value in the output and paste it somewhere. Or I want to copy the test file path and paste it into a terminal.

[Markdown Preview](https://github.com/atom/markdown-preview) has recently added the ability to copy text from the preview pane. Maybe use whatever technique they're using. Here's the function that does it: https://github.com/atom/markdown-preview/blob/c14e5c7ac912c0ebd08224d2c501a2680a32f3ec/lib/markdown-preview-view.coffee#L153

**Comment by calebhaye** [comment]
@mcary maybe we can take a look at this one?

**Comment by calebhaye** [comment]
I'd think more than just copy it, we'd also want to be able to select and search it.

**Comment by gucki** [comment]
I don't know atom internals, but I'd assume/ suggest there should be a generic window object that handles that automatically? Having each plugin to implement that common functionality on its own would be really bad, imo. So probably open an issue there too?

**Comment by dcarral** [comment]
+1

**Comment by moxley** [comment]
Fixed

**Comment by thibaudgg** [comment]
:heart_eyes:
