### ISSUE TITLE
Rspec being run inside a feature file

### ISSUE THREAD

**Issue by trevordjones** [moxley/atom-ruby-test#62]
Hi! I'm loving ruby-test and it works perfectly inside my spec files. However, when I run it inside my feature files for cucumber tests, I noticed it was still trying to run the `rspec` command. I had changed the default settings to just include the `bundle exec` command, but even when I changed everything back to default, my feature tests were still being run with Rspec. Have I missed something? Can I provide any other information? I just downloaded the newest Atom 1.0.0 version a couple days ago and my ruby-test version is 0.9.11, which looks like the newest.

I've attached an image so you can see what it's saying in the test panel - that it's trying to run rspec with a feature file. The error it gives is that it sees ':' instead of 'end' - obviously because it's trying to run Rspec.

![screen shot 2015-06-29 at 4 10 42 pm](https://cloud.githubusercontent.com/assets/7663582/8418534/7138457e-1e79-11e5-9a98-84796c711829.png)

Thank you in advance!

**Comment by dideler** [comment]
Duplicate of #59

**Comment by trevordjones** [comment]
I apologize! I missed that issue - I will follow that one and close this. Thanks
