### ISSUE TITLE
Restore default keybindings

### ISSUE THREAD

**Issue by brian-vogogo** [moxley/atom-ruby-test#69]
Is it possible to restore the default keybindings?

After updating to 0.9.14, the keybindings invoked each function twice. So cmd-ctrl-t opened two test windows running the tests twice. I opened the ruby-test settings and unchecked "enabled keybindings". Now that option is gone so I cannot check it. I've tried reinstalling ruby-test.

**Comment by sunkibaek** [comment]
I have the same issue with 0.9.14: it runs the test twice (two test out panel at the same time) no matter how I run them -- via shortcut, from menu or from cmd + shift + p.

**Comment by moxley** [comment]
I cannot reproduce the issue. It seems very unlikely that something new in 0.9.14 is causing this. Here are the changes: https://github.com/moxley/atom-ruby-test/compare/63a6a89596f24bbeb4631832f965a2ce8feaf82c...d1dfbfe4f94a7999be8fb0173398cdca57db209f

What packages do you currently have installed, and what key binding customizations do you have?

**Comment by sunkibaek** [comment]
Community packages installed:
advanced-open-file
highlight-selected
language-liquid
language-rspec
linter-coffeescript
markdown-writer
minitest-snippets
rails-latest-migration
ruby-test
script

Custom keybindings:
```
'.platform-darwin atom-workspace':
  'alt-cmd-n': 'advanced-open-file:toggle'
```

Under the keybinding settings of `ruby-test` they are all listed twice -- not sure if that was intended:
![screen shot 2015-09-12 at 11 12 22](https://cloud.githubusercontent.com/assets/1668601/9829448/4915d5c4-593f-11e5-95db-f88946beccba.png)

**Comment by brian-vogogo** [comment]
I agree, feels like an Atom issue. I'll try there.

Community Packages:
atom-beautify
atom-ctags
clipboard-history
expand-region
highlight-selected
last-cursor-position
rails-transporter
ruby-test
sort-lines

The only common package with @sunkibaek is clipboard-history.

**Comment by brian-vogogo** [comment]
FYI... for now I've fixed this by putting this in my keymap (Atom -> Open your Keymap)
```
'atom-workspace':
  'cmd-ctrl-x': 'ruby-test:toggle'
  'cmd-ctrl-y': 'ruby-test:test-all'
  'cmd-ctrl-t': 'ruby-test:test-file'
  'cmd-ctrl-r': 'ruby-test:test-single'
  'cmd-ctrl-e': 'ruby-test:test-previous'
  'cmd-ctrl-c': 'ruby-test:cancel'
```

**Comment by buren** [comment]
https://github.com/moxley/atom-ruby-test/issues/69#issuecomment-140115454 worked for me too :+1:

**Comment by jamescarney3** [comment]
nice
