### ISSUE TITLE
Allow copying of text in the test pane

### ISSUE THREAD

**Issue by ddarren** [moxley/atom-ruby-test#76]
It would be really nice to allow a user to copy text from the test pane after a test has been run. For example, if an exception occurred in a gem and you like to inspect the line of code that threw the exception, then copying the 100 character gem file path and pasting in your terminal would be a lot easier than having to type it in.

I'm not Atom developer, but perhaps the fix in this link would work: https://github.com/rgbkrk/atom-script/pull/79

**Comment by moxley** [comment]
This was resolved months ago: https://github.com/moxley/atom-ruby-test/pull/68
Original issue: https://github.com/moxley/atom-ruby-test/issues/6

Do you have a recent version of ruby-test?

**Comment by ddarren** [comment]
I believe so since I just installed Atom a few days ago. The version I have is 0.9.16. I'm using a Mac with Yosemite BTW.

**Comment by ddarren** [comment]
Hmmm... seems like this problem is also happening in my Markdown bundle preview pane even when using the "right-click" context menu to copy. Might be something specific to my Atom install... I'll continue looking into this on my end.

**Comment by pluff** [comment]
Same here. but I'm using dev version of atom "1.3.0-dev". atom-ruby-test version 0.9.16, Mac OS

**Comment by jbrowning** [comment]
I too am experiencing this issue with ruby-test 0.9.16 on Atom 1.1.0 (stable).

**Comment by noseglid** [comment]
I am the maintainer of the [atom-build](https://github.com/noseglid/atom-build) package and I've had similar reports: https://github.com/noseglid/atom-build/issues/221. I found this issue on the Atom repo https://github.com/atom/atom/issues/9548, it appears to be a regression in Atom.

**Comment by thibaudgg** [comment]
Same issue with atom 1.2.2, really annoying!

**Comment by inertia186** [comment]
Same issue.  Atom 1.2.4, ruby-test 0.9.16, Mac OS X.
