### ISSUE TITLE
How can it run single rails minitest?

### ISSUE THREAD

**Issue by brancusi** [moxley/atom-ruby-test#85]
How can we run a single minitest in rails.

```ruby
test "can view resource" do
...
end
```

becomes the following under the hood in rails:

```ruby
def tets_can_view_resource
...
end
```

using `bin/rake test {relative_path} {regex}`
doesn't account for this conversion. Any ideas?

**Comment by brancusi** [comment]
Saw the other comment on this. Using zeus now to run. Works great!

**Comment by brilnius** [comment]
For those landing on this issue like me, I made a Pull Request attempt (#117) for this annoying limitation
