### ISSUE TITLE
Suggestion: Command Prefix

### ISSUE THREAD

**Issue by andypike** [moxley/atom-ruby-test#94]
Hi,

I'm interested in contributing a feature that would really help my workflow. I frequently switch between different projects, some are standard Rails apps but others are Docker based apps. For these Docker apps I need to change the run commands to have `docker-compose run ...` before the usual test runner command. Of course, I can just open the settings and change the commands but I'm wondering if there is a feature I can help add here to support a better way of doing this.

I'd be interested in your thoughts in the best way to approach this and also if it's something that would be merged should I do it.

Some ideas to get the ball rolling:

* Add a setting called Command Prefix (or similar) which allows you to specify any prefix and will prepend it to all run commands.
* The setting should have an enable checkbox so I can easily enable/disable it when switching projects
* It would be awesome if the package could workout when you use this prefix. In my case, if a `Dockerfile` file is present in the root. But I wonder if there is a more generic way we could do this that works for other scenarios.

What do you think?

Regards

Andy

**Comment by moxley** [comment]
Hi @andypike, this is a very well thought out suggestion. Fortunately, there is already an elegant solution: https://github.com/moxley/atom-ruby-test/blob/master/doc/switching-settings-between-projects.md. Let me know if there are any issues with this solution.

**Comment by andypike** [comment]
Thanks @moxley that looks exactly what I need (and will be useful for other packages). I'll give it a try. Thanks for all your hard work on this package, it's very much appriciated! 

❤️ 💚 💛 💜 💙
