### ISSUE TITLE
Update Documentation for running single file test

### ISSUE THREAD

**Issue by zeroryu** [moxley/atom-ruby-test#97]
Currently, you have to make sure that the platformio-ide terminal settings on working directory is set to "Project" level. the {relative_path} will not run if you set it other ways.

Another option, would it make sense to provide just the {filename} on top of the {relative_path}? that way the ide will be more flexible to use with

**Comment by nolanpro** [comment]
@zeroryu Thanks, I updated the documentation in a PR. Separating the filename from the relative path is definitely something worth looking into.
