### ISSUE TITLE
Focus issue

### ISSUE THREAD

**Issue by spilin** [moxley/atom-ruby-test#99]
When i run spec for a specific line, it opens up a terminal and cursor goes there instantly.. Previously cursor stayed in the editor. Is there a way to preserve old behavior without actually closing terminal? Cause now every time i run test, i need to use trackpad to return focus.

**Comment by nolanpro** [comment]
Thanks @spilin I'll look into this

**Comment by spilin** [comment]
Awesome!!! Tnx alot 👍
